### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'help'

### ISSUE THREAD

**Issue by NagaPadma** [Agricultural-Robotics-Bonn/pagnerf#5]
![image](https://github.com/Agricultural-Robotics-Bonn/pagnerf/assets/117601878/f4255252-530b-4423-b9b0-046df0a6bce2)
can you please help me to reslove this issue.

**Comment by LvisRoot** [comment]
Hi @NagaPadma, that should get fixed if you use [kaolin v0.1.1](https://github.com/NVIDIAGameWorks/kaolin-wisp/releases/tag/v0.1.1).

Let me know if it works.

**Comment by LvisRoot** [comment]
@NagaPadma, Please let me know if you're able to run the training script with kaolin v0.1.1

**Comment by NagaPadma** [comment]
> @NagaPadma, Please let me know if you're able to run the training script with kaolin v0.1.1

Hii, sure, I havent tried it yet. I will keep you posted.

**Comment by NagaPadma** [comment]
Hiii, i tried it with wispv0.1.1 it worked.

Looks interesting. 

Thanks for your quick support @LvisRoot
