### ISSUE TITLE
KeyError: 'img_mu'

### ISSUE THREAD

**Issue by emag2425** [Agricultural-Robotics-Bonn/pagnerf#6]
Hello, 

I tried to run the train.sh,  but I am getting a Key Error -- 

agrobot_base.py", line 57, in __init__
    self.stds = self.dataset_config["img_mu"]
KeyError: 'img_mu'

I checked the BUP_20.yaml and noticed there is not a key for "img_mu" or "img_stds", but there is one for "image_sets".  Is there meant to be keys for img_mu or img_stds?

**Comment by LvisRoot** [comment]
Hey @emag2425,

Actually you don't need `img_mu` nor `img_stds` for to run PAg-NeRF. But is very weird that  those are not in the yaml file :thinking: .

Is that the `yaml` you'v got from  running `bash scripts/get_bup20.sh `?

Could you share the `yaml` file you have?

**Comment by emag2425** [comment]
Yes, I ran `bash scripts/get_bup20.sh`  and this is the yaml I got  (converted to .txt for upload)

I commented out the line 57 and 58 in agrobot_base.py since you said _mu and _stds aren't needed.

I also ran into the TypeError issue [here](https://github.com/Agricultural-Robotics-Bonn/pagnerf/issues/5#issue-2260745833).  
I'm on kaolin-wisp version 0.1.2, are you suggesting downgrade to 0.1.1?

[BUP_20_yaml.txt](https://github.com/Agricultural-Robotics-Bonn/pagnerf/files/15199893/BUP_20_yaml.txt)

**Comment by LvisRoot** [comment]
@emag2425 that is very weird, I'll check what yaml file is in the uploaded files.

You're right, you don't actually needs those values, that's from an old dataloader.

Also downgrade to wisp 0.1.1 PAg-NeRF is not compatible with 0.1.2.

**Comment by emag2425** [comment]
Yes, changing to 0.1.1 fixed this.  Thank you for all the help!

**Comment by NagaPadma** [comment]
hey @emag2425 how did you able to  install kaolin-wisp v0.1.1, I tried installing but its getting installing v0.1.0. 
![image](https://github.com/Agricultural-Robotics-Bonn/pagnerf/assets/117601878/2c852567-3025-4d3e-8a92-5cbb543538ae)

**Comment by emag2425** [comment]
@NagaPadma   I also got kaolin-wisp v0.1.0 when I installed from source

**Comment by LvisRoot** [comment]
Hey @NagaPadma and @emag2425, If I remember correctly, Kaolin has an issue where it reports being version 0.1.0 despite you having version 0.1.1. so ignore what the installer says.

Just be sure to remover any previous kaolin installation with `pip remove kaolin-wisp`, then checkout [0.1.1 tag](https://github.com/NVIDIAGameWorks/kaolin-wisp/releases/tag/v0.1.1) and install.

You can check which version you have e.g. by checking the code copied into your virtual environment folder and looking at `kaolin-wisp/wisp/models/nefs/base_nef.py`. That one should look like [this](https://github.com/NVIDIAGameWorks/kaolin-wisp/blob/v0.1.1/wisp/models/nefs/base_nef.py).

Hope that helps.
